# Generated by Django 4.2 on 2023-05-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bulk_sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100, null=True)),
                ('recipient', models.CharField(max_length=100, null=True)),
                ('body', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='buy_airtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', ' MTN'), ('GLO', 'GLO'), ('AIRTEL', 'AIRTEL'), ('9MOBILE', '9MOBILE')], max_length=20, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biller', models.CharField(choices=[('GOtv', 'GOtv'), ('StarTimes', 'StarTimes'), ('DSTV', 'DSTV'), ('Showmax', 'Showmax'), ('IROKOTV', 'IROKOTV')], max_length=20, null=True)),
                ('payment_item', models.CharField(max_length=20, null=True)),
                ('smartcard_number', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sell_to_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', ' MTN'), ('GLO', 'GLO'), ('AIRTEL', 'AIRTEL'), ('9MOBILE', '9MOBILE')], max_length=20, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('percent_deducted', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SME_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', ' MTN'), ('GLO', 'GLO'), ('AIRTEL', 'AIRTEL'), ('9MOBILE', '9MOBILE')], max_length=20, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('data_plan', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
