# Generated by Django 4.2 on 2023-06-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appservices', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
